# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/debian-7.6"

  config.vm.define "primary" do |srv|
    srv.vm.network "private_network" , ip: "10.1.1.100"
    srv.vm.provision :shell, path: "bootstrap-host.sh", args: ["primary"]
    srv.vm.synced_folder ENV['VAGRANT_BOOTSTRAP_DIR'] || File.join(ENV['HOME'], 'vagrant-bootstrap'), "/mnt/bootstrap"
  end
end
